//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line_Segment
    {
        public int SegmentID { get; set; }
        public string Location { get; set; }
        public string Type { get; set; }
        public Nullable<int> Electrified { get; set; }
        public Nullable<double> Max_Weight { get; set; }
        public Nullable<int> SpeedLimit { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> LineID { get; set; }
    
        public virtual Line Line { get; set; }
    }
}
