//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Line()
        {
            this.Line_Segment = new HashSet<Line_Segment>();
        }
    
        public int LineID { get; set; }
        public Nullable<int> OperatingCompanyID { get; set; }
        public Nullable<int> StartFacilityID { get; set; }
        public Nullable<int> EndFacilityID { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual Facility Facility1 { get; set; }
        public virtual Operating_Company Operating_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Line_Segment> Line_Segment { get; set; }
    }
}
