//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RailwayDBEntities : DbContext
    {
        public RailwayDBEntities()
            : base("name=RailwayDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<FacilityType> FacilityTypes { get; set; }
        public virtual DbSet<Line> Lines { get; set; }
        public virtual DbSet<Line_Segment> Line_Segment { get; set; }
        public virtual DbSet<Operating_Company> Operating_Company { get; set; }
        public virtual DbSet<Operator> Operators { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Wagon> Wagons { get; set; }
        public virtual DbSet<WagonType> WagonTypes { get; set; }
    }
}
