//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wagon
    {
        public int WagonID { get; set; }
        public Nullable<int> Payload { get; set; }
        public Nullable<int> Volume { get; set; }
        public string Dimensions { get; set; }
        public Nullable<int> Tare { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> WagonTypeID { get; set; }
        public Nullable<int> OperatorID { get; set; }
    
        public virtual Operator Operator { get; set; }
        public virtual WagonType WagonType { get; set; }
    }
}
